### ISSUE TITLE
feat: Make Layout customizable through configuration rather than code

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/example-storefront#288]
Most implementers are going to want to change the Layout to match their designs. Right now the only way to override this is to modify the `_app.js` file (albeit a simple and easy change). It would be great if this could be changed in configuration outside of code so that it's easier to merge in upstream changes.

The simplest method might just to be to configure the import path for a `<Layout>` component

**Comment by aldeed** [comment]
I think specifically what could be improved here is this block of code in `_app.js`:

```js
                {route === "/checkout" || route === "/login" ? (
                  <StripeProvider stripe={stripe}>
                    <Component pageContext={this.pageContext} shop={shop} {...rest} {...pageProps} />
                  </StripeProvider>
                ) : (
                  <Layout shop={shop} viewer={viewer}>
                    <Component pageContext={this.pageContext} shop={shop} {...rest} {...pageProps} />
                  </Layout>
                )}
```

This logic is rather specific, in a file that is otherwise very generic. If we pull out that block into a separate component, we can have a much smaller file where common customizations happen, and `_app.js` will generally not need to be touched.

Also:
- Move everything related to Stripe to it's own component so that it's easier to remove that if not using Stripe.
- Can we just add StripeProvider always rather than route-specific? I don't think it will make much difference performance-wise.
- Maybe try to figure out a little more declarative pattern around which routes get which layout wrappers.

**Comment by samkelleher** [comment]
Feedback: When implementing layout changes, we actually continued with a fork under the assumption that continued updates from upstream would no longer be possible.

The _app.js file was only touched once, and was indeed to remove the StripeProvider. There are a few points like this where Stripe needed removing, the biggest friction was within CheckoutActions which is built upon Stripe elements, which no longer function at all once Stripe is removed.

All the files in the `pages` directory were modified. The issue with Layout changes in configuration was that there is often so much variance that the config is difficult to manage, and simply replacing or editing the page and layout components directly was simpler.
