### ISSUE TITLE
Billing address is lost when the user refreshes

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/example-storefront#415]
# Save billing address to cart

### Summary description
Currently, cart's billing address is only saved in the client's state so it is lost when user reloads the page.

### Rationale for why this feature is necessary
When user leaves the cart and reloads it, they should not need to fill in the billing address again. For Paypal payments in particular, when user is redirected to another page, the cart's billing address is completely lost.

## Proposal

- User experience: When a user clicks `Save and continue` on the Payment Method checkout action, save an object with `billingAddress`, and associated payment method data, like `stripeToken`.

- Data: Create a `onSetPaymentMethod` mutation that triggers a `setPaymentOptionMutation` mutation

**Comment by machikoyasuda** [comment]
@ajporlante 

The PayPal mock ups so far do not collect `billingAddress` at all: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?tag=PayPal 

Does a user have to fill out and submit their `billingAddress` before they get redirected PayPal? Cos if so, we need a redesign from the UI side (along with making sure the Starter Kit saves and displays billingAddress).

**Comment by ajporlante** [comment]
Does a user have to fill out and submit their billingAddress before they get redirected PayPal?  - Yes. But this feature is not just about Paypal. I think this is a necessary feature even for Stripe or credit card payments in general.

**Comment by machikoyasuda** [comment]
@aldeed Was there a reason why we don't save PaymentMethod/billingAddress in the backend? Does this proposal sound good?

**Comment by aldeed** [comment]
@machikoyasuda In general we're just avoiding storing anything in the database until we need it, and the billing address is part of each specific payment UI, so we don't need it until the payment is submitted at the very end.

@ajporlante First, I don't understand why we'd collect a billing address before redirecting to PayPal. I think we'd wait to see if PayPal gives us one when it redirects back, and if not, then collect it. Although I thought that was all part of the PayPal flow anyway.

Second, the billing address form/selection should be part of the specific payment method UI. It's not intended to be shared between payment methods. So if one payment method needs an address it should collect it but if another one doesn't it should not. If the UI / checkout components are not currently set up this way, we should change that.

So that means that the PayPal method will need its own checkout component, which can collect a billing address if necessary. When you implement that in the starter kit, ideally it should not prompt for the billing address until after redirected back from PayPal. if it's truly necessary to ask for a billing address before the PayPal flow, then you can save it in MobX and persist that part of the state in local storage.

**Comment by zenweasel** [comment]
@aldeed So even if a payment provider saves the billing address, it's not being recalled on refresh. So this seems like it still needs to be resolved directly in the starter kit. So while some payment methods may not save it, even if they *do* save it, currently we lose it if the user refreshes which seems like a fairly serious flaw.

**Comment by zenweasel** [comment]
@aldeed Why is this happening for billing address and not shipping address. Certainly there are fulfillment methods that don't require a shipping address and do require a billing address e.g. digital downloads.

**Comment by aldeed** [comment]
@zenweasel Correct, I believe shipping address is collected as part of the fulfillment group based on which type of fulfillment you've chosen for that group. Currently there is only "shipping" type, but when "pickup" and "digital" are added, those wouldn't necessarily show the shipping address and method steps.

If you're asking why we store shipping address on a cart in the db but not billing address, it's because we made the decision (for security and privacy reasons) to no longer have the cart plugin be at all involved in payment data. The billing address, if one is needed, is only needed by the payment plugin, which doesn't come into play until you place the order at the end of checkout.
- If any payment data needs to be persisted PRIOR TO placing the order, we leave it up to the payment plugin to determine the best and most secure way to do that.
- If any payment data needs to be persisted ON the order, that's what the generic `PaymentData` object is for.

**Comment by zenweasel** [comment]
@ajporlante Can we close this issue? Has this been handled?

**Comment by janus-reith** [comment]
So what to do in cases where a redirect is required and the plugin doesn't handle the billing address?

This made we think of how to persist the required data for these redirect payments at all, as usually there is additional information needed. I believe before we used to expose routes on the backend for this that grab the necessary data and then redirect. But now I wonder if such redirects could also be securely handled in the cart page on the frontend, communicating necessary data to the backend over GraphQL then.

While this certainly requires additional logic like the routes with parameters for each plugin that doesn't matter here, what I'm thinking about would be some generalized client implementation `pendingPayment`, which could also include the billing address? (But should never include any authorized tokens that could be misused)


And regarding the Paypal example, I'm having issues with the way this works from the UX experience:

While I certainly get the logic of authorizing the payment first, doing whatever is necessary then like asking for the billing address and finally clicking the place order button, this could result in a lot of non-finished carts. A lot of users are used to completing a checkout by just following the Paypal flow.

Therefore I ended up making Paypal a simple radio option without a form, and then replaced the final checkout step to show the Paypal button instead of" Place order" if Paypal was selected. I am not using the redirect flow but a popup, as the Paypal docs suggest that other implementations are outdated.
