### ISSUE TITLE
Cannot edit address in checkout

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#494]
Type: **critical**

**Describe the bug**

Address form "Save and continue" button disabled when editing an address

**To Reproduce**
1. Add products to cart and checkout
2. Enter a valid address, then "Save and continue"
3. "Change" the address
4. See error the "Save and continue" button disabled, even if you modify fields

**Expected behavior**

Save button should not be disabled

**Screenshots**

![checkout___reaction](https://user-images.githubusercontent.com/42217/52079874-6348c880-254b-11e9-9f82-b7491b0cbd33.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mohajve
 - Browser: Chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by mikemurray** [comment]
supercritical

**Comment by zenweasel** [comment]
hypercritical

**Comment by janus-reith** [comment]
Has there been any progress regarding this?

**Comment by spencern** [comment]
@mikemurray has this been resolved or discussed?

**Comment by janus-reith** [comment]
I could still observe this issue in rc11 / current dev channel.

**Comment by spencern** [comment]
Thanks @janus-reith . 
@nnnnat can you take a look at this at some point?

**Comment by nnnnat** [comment]
@spencern I'll take a look at this today

**Comment by janus-reith** [comment]
I can still that error when adding an address as guest, then leave or reload the cart page and try editing it afterwards, or as a logged in user that already has an address.
In the second case, I can't edit the address from the beginning.

**Comment by janus-reith** [comment]
The error originates here in the component library: [ShippingAddressCheckoutAction.js#L196](https://github.com/reactioncommerce/reaction-component-library/blob/5e8ec3676cfcd27020f1878b8cf6c6ac3c5c02aa/package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js#L196)

The first time the data is entered, these are the fields that get evaluated(passes as `value`) :
address1
address2
city
country
fullName
isCommercial
phone
postal
region
__proto__: Object

After saving and reloading, there are these additional values:

company: null,
isBillingDefault: false,
isShippingDefault: false,
__typename: "Address"

The check fails because of the company field being null

I guess there are several ways to handle this, the easiest would probably be to edit `isFormFilled` to also skip `company`, like it is already done with `address2`.
[ShippingAddressCheckoutAction.js#L182](https://github.com/reactioncommerce/reaction-component-library/blob/5e8ec3676cfcd27020f1878b8cf6c6ac3c5c02aa/package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js#L182)

Apart from that it seems like the way the field company is used could be reconsired.

**Comment by janus-reith** [comment]
Created the accompanying ticket here: https://github.com/reactioncommerce/reaction-component-library/issues/416

**Comment by janus-reith** [comment]
IMHO a fix should be incorporated pretty fix, this is a problem every new user who starts from scratch with the whole current `reaction-platform` will run into.

During first checkout the user will notice that no shipping options are configured.
The user would go to the dashboard, create a shipping option, go back to the starterkit and wonder that nothing changed.

Usually, at least editing the entered shipping address would then refresh the shipping options, but as that won't work the user is stuck and needs to delete the stored session manually in order to proceed.

**Comment by spencern** [comment]
@kieckhafer @mikemurray @nnnnat @janus-reith 
Seems like this is an issue that we need to resolve - do we have a sense of the effort level required to fix?

@janus-reith if you want to take a crack at this, we'd definitely look at a PR to resolve this. If not we'll try to prioritize as soon as we can

**Comment by janus-reith** [comment]
I already narrowed it down and sovled the issue here:
https://github.com/reactioncommerce/reaction-component-library/pull/417

Just need to pull that change and release an updated version of the component library and use that in the starterkit.

A more sophisticated solution that takes cases into account where company will be a usable and maybe required field will probably just become relevant if we have a way to set that behaviour somewhere, so this PR should do the job for now.

**Comment by willopez** [comment]
Will be closed in https://github.com/reactioncommerce/example-storefront/pull/588
