### ISSUE TITLE
login and signup pages  gives  The OAuth2 request resulted in an error.  

### ISSUE THREAD

**Issue by MoustafaBayommy** [reactioncommerce/example-storefront#502]
**Describe the bug**
when ever i am trying to sign in or sign up it gives me 

**To Reproduce**
1. Go to home page
2. Click on  sign in or create new account

this will produces that error 

The OAuth2 request resulted in an error.

    Error: invalid_request
    Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed
    Hint: The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.
    Debug:

You are seeing this default error page because the administrator has not set a dedicated error URL (environment variable OAUTH2_ERROR_URL is not set). If you are an administrator, please read the guide to understand what you need to do. If you are a user, please contact the administrator.

**Comment by amazedge** [comment]
I too face exactly same issue. By any chance, have any one fixed this issue?
What could be the solution for this..?  

regards
Bala

**Comment by impactmass** [comment]
@MoustafaBayommy @amazedge were you able to get past the error?

**Comment by impactmass** [comment]
I see this is an old issue (and thus late response), but the error hint you pasted, shows where the issue lies:

`The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.`

When the auth flow is initiated, the storefront sends along a [callbackUrl](https://github.com/reactioncommerce/example-storefront/blob/516ace42a7ce529e8e9dcde13b39eb6c1c0ec149/src/serverAuth.js#L21). It must match one of the [redirect_uri's](https://github.com/reactioncommerce/example-storefront/blob/master/bin/create-hydra-client.js#L28) created for the storefront in Hydra. 

How to fix:
- Check the client config you have in Hydra. [Relevant Hydra doc](https://www.ory.sh/docs/hydra/debugging#wrong-or-misconfigured-oauth-20-client)
From the reaction-platform directory, cd into reaction-hydra and you can run:
`docker-compose run --rm -e "HYDRA_ADMIN_URL=http://hydra:4445" hydra clients get example-storefront`
- Inspect the `redirect_uris` from the response, and check what you have listed in your .env (OAUTH2_REDIRECT_URL)
- Edit your env to match. This could have happened if you had an older version with a different value for that env.

Re-open if all you do all that, and still get the error.

**Comment by Jorgelg13** [comment]
Hi, I have the same problem, someone can help me, I am trying to get the most up-to-date version.

**Comment by MoustafaBayommy** [comment]
@impactmass  thank you it already solved  ,after i read Hydra docs  it was wrong configurations.

**Comment by mathiasfc** [comment]
> @impactmass thank you it already solved ,after i read Hydra docs it was wrong configurations.

@MoustafaBayommy can you share the solution in details? thanks.
