### ISSUE TITLE
Missing Shopify API hook

### ISSUE THREAD

**Issue by RoytenBerge** [reactioncommerce/example-storefront#589]
Dear All,

In the following video from 2017, reaction features a feature where it is possibleto upload  shopify items using an API key:
https://youtu.be/Y-p7ZrIBZCQ?t=510
I have been looking for a certain feature, but I can't find it in the new release.
Since it is an old video, I can imagine it being removed, however I would love to make use of this feature.
Was this feature removed or where can I still find this?

**Comment by spencern** [comment]
Hi @RoytenBerge 
We've removed this feature from the core application and moved it to our community-supported library of features. I think the basics of how this works _should_ still be correct, but there is likely some work that will need to be done in order to use this plugin with v2.5.0 of Reaction.

If you do hack on it and get it working, I'd be happy to look at a PR to update it.

Here's a link to the project:
https://github.com/reaction-contrib/meteor-connector-shopify
