### ISSUE TITLE
Shipping Handling is calculated twice at checkout

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/example-storefront#590]
Type: **critical**

**Describe the bug**
Shipping Handling is calculated twice in Order
At checkout getting error "Client provided total price {amount} for order group, but actual total price is {amount}"while placing order

**To Reproduce**
Please provide starting context, i.e. logged in as a user, configure a particular payment method.

In admin portal, add Flat rate with any value in handling and rating (eg: Handling=3, Rate=10)
Add a product to cart and checkout and place order
Attached screenshots:
Here,
Product price is 100
Shipping Handling is set 3
Shipping Rate is set 10.
Order total is $113 (100 + 3 + 10)

Error: Client provided total price 113.000 for order group, but actual total price is 116.000

Actual total price calculates Handling price twice

**Expected behavior**

**Screenshots**
![Screen Shot 2019-09-25 at 9 26 13 AM](https://user-images.githubusercontent.com/12378687/65812709-02c46680-e180-11e9-8da6-a6a6b44c7457.png)

![65306114-7f7c9280-db39-11e9-8ff1-67a5335e7a6b](https://user-images.githubusercontent.com/12378687/65812710-0657ed80-e180-11e9-8fd4-b03fbd22bd45.png)

**Desktop (please complete the following information):**
 - OS: macOS version 10.14.6
 - Browser Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

initially reported here: https://github.com/reactioncommerce/reaction/issues/5572

**Comment by vigyano** [comment]
https://github.com/reactioncommerce/reaction/issues/5572#issuecomment-534587460

**Comment by vigyano** [comment]
@aldeed any updates on fix?

**Comment by aldeed** [comment]
This hasn't been prioritized for anyone to work on but PRs with fixed would be reviewed and accepted. To copy my suggestions into this issue:

Note that even with perfect refetching on the client, this error can happen. For example, a price change may be published by an admin right before you press the Place Order button. The storefront should do a nicer job of detecting this error, refreshing the screen, and helping the user place their order.
- set the cart checkout data query to poll every few seconds
- refetch the cart checkout data when moving to the final review step
- detect when this mismatch error comes, refetch the cart checkout data, and show a nicer error like “Some prices may have changed since you started checking out. Review the updated order totals and place the order again if you still want to place it.”
- make sure Apollo is updating the cache with the updated cart that comes back from each mutation at each step of checkout

Of these, "refetch the cart checkout data when moving to the final review step" will likely fix the largest number of situations.
