### ISSUE TITLE
Changing quantity on Cart page removes ProductItem while onFocus is active

### ISSUE THREAD

**Issue by HarisSpahijaPon** [reactioncommerce/example-storefront#652]
Type: **minor**

**Describe the bug**
Changing the quantity value on Cart removes the item when quantity is undefined/null while typing. 
When filling out a specific number the cart item will be removed once the number of the quantity is changed by typing. 

**To Reproduce**
1. Add an item to cart
2. Select quantity for any item on `/cart` (`Cmd + a` on macOS)
3. Backspace the quantity (this is a normal user interaction)
4. Item is removed once the value is removed

**Expected behavior**
I expect the item to still be in my cart while filling out the desired quantity

**Screenshots**
![/Cart page](https://user-images.githubusercontent.com/57092814/73260210-be96b080-41c9-11ea-8218-a105e7b57bac.png)

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser Chrome (haven't tested other browsers)

**Additional context**
Checking if cart item should be removed must happen on `!onFocus` trigger. Not when the amount is being filled out.

**Comment by bugfloyd** [comment]
I choose this issue for my first contribution to the project. After looking around in the code base, I tried to debug the issue. However, I need advice to make some decisions.

The straightforward approach to implement the suggested solution by @HarisSpahijaPon , is updating the quantity input field which is defined in `@reactioncommerce/components/QuantityInput/v1`.

The simplest update is to remove the `handleChanged()` method invocation from the `handleQuantityInputChange()` method and move it to a new `handleQuantityInputBlur()` method and use the later one as the value for `onBlur` property while rendering the component.

I tested this approach and it works fine as requested. Checking if cart item should be removed happens on blur trigger and the user is able to remove the current quantity value and enter new one and click around to focousout from the input to get updated rates, etc. However I'm thinking about some UX downsides:
1. The fact that user needs to click somewhere else or use Tab key, is by itself annoying and misguiding, specially on mobile devices. In this case, this problem is more remarkable since we have 2 buttons to increase or decrease the quantity, which trigger `handleChanged()` method immediately. So user may use these buttons and would see a real-time change in total rates, but changing the input directly won't effect the totals, until clicking around.
2. In my thoughts, the whole idea about auto-vanishing items with zero quantity is very annoying. Any user at some point may click on the decrement button by mistake or try to delete the quantity and think a while to enter new one and meanwhile click on somewhere else on the screen! Boom! Item vanishes and they have to find that exact product again!

I suggest implementing the early solution on `@reactioncommerce` package for now, since the current situation in which users are not able to remove the quantity before entering new one, is the worst case.

And I suggest 2 plans to solve this problem in a more user-friendly way:
1. Add a new "Update" button on the cart page and mini-cart component. Doing so, users have to press that button after editing the quantity in anyway they like. This approach is more predictable and user-friendly and also implemented in many popular e-commerce solutions. If a user enters zero quantity for an item, by clicking "Update", that Item will vanish.
2. Apply a minimum value of 1 for the quantity fields. The decrement button will work as we have on the single product pages. In this approach, clearing the value by user will considered 1, until they enter a new value or focus out from the input field to see  "1" as the quantity. To remove an item, they may use the "Remove" button. We may even want to implement a auto-vanishing when a user enters "0" explicitly and then focuses out of the input.

What do you think? Should I create a PR to implement the blur solution for now? What do you think about 2 approaches to solve auto-vanishing problem?

**Comment by ghost** [comment]
> In my thoughts, the whole idea about auto-vanishing items with zero quantity is very annoying.

Agreed on this pain point in the UX. As this issue is resolved I'd suggest tackling this with a confirmation dialog when decrementing items to quantity 0 and before the item is removed from the Cart unless there's an easily accessible view of product history available to users.
