### ISSUE TITLE
Remove or refactor segment analytics 

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/example-storefront#676]
Type: refactor

**Describe the refactoring**
Remove or replace `custom/analytics/provider.example.js` and `custom/analytics/segment.js` depending on how we implement this. For additional context see: https://github.com/reactioncommerce/example-storefront/pull/667#issuecomment-616207068

**Comment by jhonsfran** [comment]
hi @willopez I'm really interesting on work in this feature but I'm not sure how can approach it. Could you tell me how can I help?

**Comment by willopez** [comment]
Hi @jhonsfran1165 and thanks for your interest in Reaction. It would be great if you can help with this effort, the main goal is no remove many of the HOC(Higher Order Components) that are currently used to  implement tracking. HOC add too much unnecessary complexity and we believe is not the best strategy for this feature. With that said, the idea is to used a hooks(React hooks) based tracking implementation, @janus-reith and I had a brief discussion regarding this, hopefully he can chime in. I would suggest the first step would be to research potential candidates for packages that can be used to implement tracking. We currently use [https://github.com/nytimes/react-tracking](https://github.com/nytimes/react-tracking) with HOCs, perhaps they support hooks now.

**Comment by janus-reith** [comment]
@jhonsfran1165 Thanks for offering your help, highly appreciated!

It seems like react-tracking supports hooks by now, however, I'd be happy with any solution which as @willopez pointed out, doesn't add any unnecessary complexity and stays provider-agnostic. Parts of the existing implementation might still be useful, or completely obsolete with the latest version of react-tracking or any potential other library.
I didn't check that further, but at least the provider abstraction as seen in `custom/analytics` seems like an approach worth keeping.
Also, you might run into some Nextjs/SSR specific obstacles to keep in mind, but most should be easy to resolve.

A main concern would be to avoid spreading the tracking events across several components which otherwise serve a presentational purpose, as done in the past. Preferably, all tracking events would be fired from inside the hooks that handle a specific logic like adding cart items, or also from the context providers if there is a valid use case.
That would be perfectly in line with the general way things were implemented the past months, or are about to be, as there still are a few places left in the storefront codebase where data-related logic is nested in some components. But if you stumble upon these and this would block you from proceeding, I'd be happy to quickly provide a refactor as soon as it becomes relevant.

To get started, I'd suggest taking a look at the existing tracking implementation in the previous release branch, and how other things work out with hooks now, and then evaluate wether to use `react-tracking` or alternatives.
Then try to wire that up, probably somewhere near `_app.js` which works across pages.

You can get an idea what was tracked previously by looking at the functions in `/lib/tracking`.
Then pick some event like adding cart items and try to implement it in the useCart hook.

Feel free to reach out if you have further questions or need clarification!

**Comment by janus-reith** [comment]
I had a quick look at the react-tracking codebase and documentation, and started to wonder If we need to use any library at all, at least I failed to find much value this provides nowadays with the way things are implemented now.

As I also found no other library yet that provides any meaningful value or reduces time to implement this, my best bet would be to just create a simple event tracking hook from scratch and make use of that in the other relevant hooks.
iI it necessary to share some state across pages or components, just create some tracking context provider to keep that state.

**Comment by willopez** [comment]
@janus-reith I agree, if a simple hook can get the job done, then let's do that.

**Comment by jhonsfran** [comment]
@willopez @janus-reith Hi guys after a while searching on the internet for a good choice I found this package that I think suits our needs. I want to know what you guys think about it.

https://github.com/davidwells/analytics

I think we can do a lot of interesting things with that library but first I want to hear your opinions. I'm trying to use it in the nextjs project and I'll let you know when I got something to show.

**Comment by janus-reith** [comment]
@jhonsfran1165 I just had a look, I like the plugin structure with the lifecycle hooks and guess that could be helpful.
 It seems to feature a resonable level of abstraction and neither the package itself nor the way you have to use it seem too bulky, also the bundled size looks ok. I'd say go for it.
By the way there also is an small accompanying package featuring a simple to use react hook and HOC for this: https://github.com/DavidWells/analytics/tree/master/packages/use-analytics

@kieckhafer @rosshadden I think you're in charge this week, any opinion on this?
@willopez Tagging you aswell as you took part in the discussion before.

**Comment by ghost** [comment]
Please don't remove Segment Analytics. It's in a great spot in `v.3.1.0` and adds tremendous value for new shops who want to start measuring KPIs without having to reinvent the wheel. As an example, here are some dashboards I was able to create using Amplitude via Segment without so much as lifting a finger on Analytics code:

<details>
<summary>Expand to view dashboard</summary>
<img width="1414" alt="Screen Shot 2020-09-12 at 23 52 56" src="https://user-images.githubusercontent.com/65664227/92999400-1c0e2080-f553-11ea-8337-04b4849c3d52.png">
</details>

**EDIT:** Thanks! I misunderstood based on the title thinking Segment removal was under consideration. I do hope whatever is integrated has parity with the existing events emitted as any changes will throw existing reports out of whack. I would like to see the `identify` event added, bc as far as I can tell that wasn't integrated yet with Analytics.js.

**Comment by janus-reith** [comment]
@balibebas As discussed above, I think the plan is not to remove segments, but find a solution that works better than the existing react-tracking based class decorators. Maybe the title of this issue could be updated to reflect that.

@jhonsfran1165 Are you still interested in working on a solution?
In the meantime, I implemented a solution based on https://github.com/davidwells/analytics for my projects needs and also have that in production already. The library is nice to use, and I really like the way providers are defined and events structured into indentify/page/event calls.
I could PR that sometime, just needs some tests and documentation.

Segment would just be one pluggable provider here which already has an official plugin available, adding new providers is simple aswell.

**Comment by jhonsfran** [comment]
@janus-reith yes I've been a bit busy but I'm still working on this. Of course, I'm using that library it's really cool.

Hopefully, I'll push something at the end of the next week.
