### ISSUE TITLE
Fix & re-enable tests or remove unnecessary code and associated tests

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#683]
Type: **minor**

**Describe the bug**

Some tests, of the few 14, no longer work at all due to a massive update. Listed below are the places where the tests live that need to be revisited.

- `lib/tracking/utils` // Disabled in package.json jest config
- `tests/integration/ssr.test.js` // `.skip` added to suite
- `lib/utils` (Moved mock data into closer folder to fix missing imports)

### Loose directions
- Use React testing library https://github.com/testing-library/react-testing-library (get rid of enzyme, and other unnecessary testing dependencies)
- Remove or fix test locations above
- Remove unused utils
- Add unit tests for utils that are used
- Add tests for hooks and GQL
- Consider some tests for components. (think non brittle testing with getByRole and getByTest)
- Work towards a path of having E2E tests with cypress or something else.

**Comment by reith-outgrow** [comment]
Maybe let's have a general overview of test we want to have in the storefront?
@mikemurray  Which one would you consider important?
Also, some options regarding the toolchain we could use changed the past years, e.g. we could decide between @testing-library/react, enzyme or react-test-renderer and I don't have a clear recommendation.

I'd like to see E2E tests introduced at some point for all the basic steps like adding to cart/checking out, most probably with cypress, and I'd like to keep them as broad in scope as possible so they would even continue to work with many storefront customizations, or would at least be easy to fix again.

Apart from that, it probably make sense to keep and maybe refactor the test for the util functions in lib/utils, I don't expect much things changing or breaking there. (Apart from the issues with babel test env as discussed)

Then it would probably also make sense to have tests available for the hooks and context Providers, as they account for much of the logic and probably will even more in some future release. (I could see them potentially becoming a separate library at some point, so I think there should be some focus on them.)

For the GraphQL Calls in there we could use `MockedProvider` which Apollo provides.
For that, I wonder what workflow we could maybe adopt to keep up with backend changes, e.g . instead of editing manually, to extract GraphQL API answers somehow or detect changes using Introspection somehow (not sure if feasible but it sounds great to not have to write most Mocks by hand).

We could have tests to detect major render changes, but preferably no Snapshots test, which would break soon when doing customizations and would eventually just be ignored by devs.

Regarding per Component testing, I'm somewhat uncertain as to what to reasonably test and to what extent, you will probably have a better overview here.

**Comment by janus-reith** [comment]
Maybe let's have a general overview of test we want to have in the storefront?
@mikemurray  Which one would you consider important?
Also, some options regarding the toolchain we could use changed the past years, e.g. we could decide between @testing-library/react, enzyme or react-test-renderer and I don't have a clear recommendation.

I'd like to see E2E tests introduced at some point for all the basic steps like adding to cart/checking out, most probably with cypress, and I'd like to keep them as broad in scope as possible so they would even continue to work with many storefront customizations, or would at least be easy to fix again.

Apart from that, it probably make sense to keep and maybe refactor the test for the util functions in lib/utils, I don't expect much things changing or breaking there. (Apart from the issues with babel test env as discussed)

Then it would probably also make sense to have tests available for the hooks and context Providers, as they account for much of the logic and probably will even more in some future release. (I could see them potentially becoming a separate library at some point, so I think there should be some focus on them.)

For the GraphQL Calls in there we could use `MockedProvider` which Apollo provides.
For that, I wonder what workflow we could maybe adopt to keep up with backend changes, e.g . instead of editing manually, to extract GraphQL API answers somehow or detect changes using Introspection somehow (not sure if feasible but it sounds great to not have to write most Mocks by hand).

We could have tests to detect major render changes, but preferably no Snapshots test, which would break soon when doing customizations and would eventually just be ignored by devs.

Regarding per Component testing, I'm somewhat uncertain as to what to reasonably test and to what extent, you will probably have a better overview here.

**Comment by mikemurray** [comment]
@janus-reith I agree that snapshot tests are too brittle. We should be going toward using `@testing-library/react` as the testing library as we already use it elsewhere. If testing of components is still helpful to us as the maintainers of the `example-storefront` base project, then testing interaction loosely with `getByRole` and `getText` and such from testing library may be more helpful. Checking for general existence and interaction rather than strict structure.

E2E tests are probably more helpful in this regard though to ensure checkout from start to finish still works. Some important details would be, can you checkout, is order summary displayed correctly with correct values, and is SSR working, can I see tags and paginate the grid.

Unit tests for hooks and GraphQL would be the best place to have robust tests. If those libs could be an external library that would make the testing even more valuable. We can always set up a `storefront-utils` package if you want to go down the direction of externalizing those things.

**Comment by willopez** [comment]
@mikemurray @janus-reith I agree with both. I'll create a new PR to remove the snapshot tests and configure react-testing-library and perhaps cypress on another PR.

**Comment by janus-reith** [comment]
@mikemurray Thanks, the `storefront-utils` package sounds great, I'd like to get back to it at a later point after refining the hooks more - Basically my plan is to avoid passing props for all data that is not ui-related or tied to the component (so only things like e.g.`hasRedBackground` are left ) - Will create a separate Issue for that. I have no experience so far with @testing-library/react, but happy to try it out, except someone else wants to take this who maybe already used it?

@willopez Sounds good. I removed all the snapshots and related tests already, not sure if there are leftovers though.

**Comment by willopez** [comment]
@janus-reith You are right, all the snapshot tests have been removed. I have started the work towards using `react-testing-library`, I just added the foundation and removed unnecessary dependencies in #686

**Comment by janus-reith** [comment]
I would like to add https://mswjs.io to the list.
It supports mocking REST and GraphQL calls by intercepting them on the network level and would allow for tests like this:
https://github.com/mswjs/msw#usage-example-1
(Example uses Jest and React Testing Library aswell )
