### ISSUE TITLE
Sitemap isn't being generated

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#712]
Type: **minor**

**Describe the bug**
The sitemap isn't being generated on `trunk` in development.

**To Reproduce**
1. Start development.
2. Navigate to `/sitemap.xml`
4. See screenshot.

**Expected behavior**
A sitemap is generated with pages for each locale present.

**Screenshots**

![Screen Capture_select-area_20200728193128](https://user-images.githubusercontent.com/65664227/88660444-4d4ca180-d109-11ea-9648-2c294ece699c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
Consider the impact of duplicative content on SEO when only the interface is translated.

**Comment by janus-reith** [comment]
The sitemap is fetched from the API over GraphQL and created there, please check your sitemap settings in the admin.
If anything doesn't work as expected, please open an issue there instead: https://github.com/reactioncommerce/api-plugin-sitemap-generator.
If you can't pinpoint an API issue to a plugin though, you could also just create an issue about it here: https://github.com/reactioncommerce/reaction

There is however one minor storefront issue visible in your screenshot due to the storefront not detecting the protocol properly and therefore using `undefined//`.
This however is resolved in the api-route version of this in the `trunk` branch, which now simply uses `CANONICAL_URL` provided from env instead of parsing the incoming request, as described here: https://github.com/reactioncommerce/example-storefront/issues/689

I'm closing this, as I don't think that the issue is related to the storefront.

**Comment by balibebas** [comment]
I've started opening issues there starting with https://github.com/reactioncommerce/api-plugin-sitemap-generator/issues/12 which may be why, in the image above, we don't see the the Tags Sitemap being generated. Given the different moving parts related to sitemap generation (API/Job Queue/Sitemap Generator) it's a bit tricky to debug. On the off chance you have any suggestions for hot to get a deubgger in the API code or if there's a doc I missed I'd appreciate the olive branch.

**Comment by ghost** [comment]
Thanks @janus-reith. I've started opening issues there starting with https://github.com/reactioncommerce/api-plugin-sitemap-generator/issues/12 which may be why, in the image above, we don't see the the Tags Sitemap being generated. Given the different moving parts related to sitemap generation (API/Job Queue/Sitemap Generator) it's a bit tricky to debug.

In the off-chance you have any suggestions for how to get a step debugger set-up in the API plugins, or if there's a doc I missed in order to do so, I'd appreciate the olive branch.
