### ISSUE TITLE
Restore ability to customize routes

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#714]
Type: **minor**

**Describe the bug**
The i18n work done on this app introduced an i18n router and removed the ability to customize routes or see what routes are available at a glance. As a result it's no longer trivial to add a custom homepage [as described](https://docs.reactioncommerce.com/docs/swag-shop-5) in the docs.

**To Reproduce**
1. Spin up a dev environment.
2. Reference the linked documentation
3. Attempt to create a custom homepage.

**Expected behavior**
Routes may be customized by the user in a non-trivial fashion.

**Screenshots**
n/a

**Additional context**
I've submitted a related documentation issue here: https://github.com/reactioncommerce/reaction-docs/issues/954

**Comment by janus-reith** [comment]
@balibebas 
Technically, nothing prevents you from creating new pages, or adding custom routes in your next.config.js.
I guess this is mainly a matter of lacking documentation, but techncially there is no functionality that needs to be restored.

Just instead of relying on a custom express server and a package that was last updated over 2 years ago, we now make use of the latest features Nextjs offers out of the box. Getting rid of the custom express server comes with other benefits, for example the storefront can now be used on serverless deployments, mainly Vercel at this time.

Interesting docs that describe the used patterns would be:

https://nextjs.org/docs/api-reference/next.config.js/rewrites
https://nextjs.org/docs/api-reference/next.config.js/redirects
https://nextjs.org/docs/routing/dynamic-routes

I wonder if we shoud close this issue since there is one in reaction-docs already, or simply rename it, as we could also need one here  regarding the update of the docs included in the storefront repo.
